### ISSUE TITLE
Failure loading the hook

### ISSUE THREAD

**Issue by XePeleato** [Olipro/LuaHook-NG#1]
I have successfully compiled the Hook, obtaining IPHLPAPI.dll and LuaHook-NG.dll, but it looks like I am missing something; I copied the libraries to the `PAYDAY 2` folder, but if I open the game, a text file named `missingsigs.txt` appears. I have had a look into the code and it looks like it reports missing functions, this is the output: 

`not found: void __fastcall(struct lua_State *,int,int)53 56 57 8b f9 8b da 8b 4f 10 8b 41 48 85 c0 74 0b 48 89 41 48 8b cf e8 64 b3`

`not found: int __fastcall(struct lua_State *,int,int)8b 44 24 04 53 56 8b d9 57 8b 73 10 33 ff ff 24`

`not found: void __fastcall(struct lua_State *,int,int)56 8b f1 e8 d8 f7 ff ff 8b 54 24 08 8b 08 e8 1d` 

It isn't very revealing but maybe someone else experienced it before. The only change I did to the code was changing `shared_mutex` by `shared_timed_mutex` (however that isn't a big deal since it should be like that, (This project is on C++14 right?)), and I also renamed the Lua files from .c to .cpp. I am compiling it with Visual Studio 2015 under Windows 10 x64.

Thanks for your time!

PS: I can upload the compiled libraries for further investigation if required.

**Comment by Olipro** [comment]
Yeah, after the game update a few of them changed and I did dig them out but forgot to push to the repo.

The new commit fixes it.

I'd be interested to see what you've done with `std::shared_timed_mutex` although I'm not quite sure the PAYDAY 2 implementation calls for it since my expectation when writing it was that construction/destruction of LuaGame instances would be infrequent to the point that fast iteration and O(n) insert/remove performance should be fine.
